services:
  - type: web
    name: url-shortener
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://demo_user:DwAxB2uTh7sWqQJn@cluster0.0thud.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: GOOGLE_CLIENT_ID
        value: 153235357696-dmn9njra045igcvp4clfljlut8uhqhhe.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: GOOGLE_CALLBACK_URL
        value: http://localhost:5000/api/auth/google/callback
      - key: JWT_SECRET
        value: "73c791e4c1c2974a07ba0899595a179f4e6797d0495cb8a0306dfb73edc6f7e187a9860c70bc4aa48c111253cd8c7aa623404fa1b019e5ecd25e52355cd9a629"
      - key: REDIS_PROXY_URL
        value: https://nehehy80pg.execute-api.ap-south-1.amazonaws.com/prod
      - key: RATE_LIMIT_POINTS
        value: "10"
      - key: RATE_LIMIT_DURATION
        value: "3600"
      - key: PORT
        value: "3000"
