openapi: 3.0.0
info:
  title: URL Shortener API
  version: "1.0.0"
  description: API documentation for the URL Shortener application.
servers:
  - url: http://localhost:3000
paths:
  /api/shorten:
    post:
      summary: Create a new short URL
      description: Creates a short URL for a given long URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  example: "https://www.example.com/some/very/long/url"
                customAlias:
                  type: string
                  example: "mycustomalias"
                topic:
                  type: string
                  example: "acquisition"
      responses:
        "200":
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: "http://localhost:3000/mycustomalias"
                  createdAt:
                    type: string
                    format: date-time
  /api/shorten/{alias}:
    get:
      summary: Redirect to original URL
      description: Redirects to the long URL associated with the given alias.
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Redirecting to original URL.
  /api/analytics/{alias}:
    get:
      summary: Get URL Analytics
      description: Retrieves analytics for a specific short URL.
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Analytics data retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalClicks:
                    type: number
                    example: 150
                  uniqueUsers:
                    type: number
                    example: 120
                  clicksByDate:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          example: "2025-02-14"
                        clicks:
                          type: number
                          example: 20
                  osType:
                    type: array
                    items:
                      type: object
                      properties:
                        osName:
                          type: string
                          example: "Windows"
                        uniqueClicks:
                          type: number
                          example: 50
                        uniqueUsers:
                          type: number
                          example: 40
                  deviceType:
                    type: array
                    items:
                      type: object
                      properties:
                        deviceName:
                          type: string
                          example: "desktop"
                        uniqueClicks:
                          type: number
                          example: 80
                        uniqueUsers:
                          type: number
                          example: 60
  /api/analytics/topic/{topic}:
    get:
      summary: Get Topic-Based Analytics
      description: Retrieves analytics for all short URLs grouped under a specific topic.
      parameters:
        - in: path
          name: topic
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Topic-based analytics retrieved successfully.
  /api/analytics/overall:
    get:
      summary: Get Overall Analytics
      description: Retrieves overall analytics for all short URLs created by the authenticated user.
      responses:
        "200":
          description: Overall analytics retrieved successfully.
