name: JavaScript Code Quality Checks

on:
  push:
    branches:
      - main
      - "feature/*" # Include feature branches if needed
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --production --json | tee audit-report.json

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  outdated-dependencies:
    name: Check for outdated dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check for outdated packages
        run: npm outdated --json | tee outdated-report.json

  prettier:
  name: Check Formatting
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run prettier
