name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, thanks for noticing this issue, create a pull request and upon review only will the pull request be merged."
        pr-message: "Thank You! for creating a PR, please wait for it to get approved."
